### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-resolve-git-ref#25]
**Description**
Running `npm test` provides the following output:

```
> @adobe/helix-resolve-git-ref@1.1.2 test /Users/stefan/projects/helix-resolve-git-ref
>  nyc --reporter=text --reporter=lcov --check-coverage --branches 100 --statements 100 --lines 100 mocha --reporter xunit --reporter-options output=./junit/test-results.xml

INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
INFO  - no external loggers configured.
[10c9db06-f4f9-41a3-b363-8ea08aa918ec] info: no external loggers configured.
[10c9db06-f4f9-41a3-b363-8ea08aa918ec] info: instrumenting epsagon.
[db376953-0363-4aa2-9b81-2e4430820bea] info: no external loggers configured.
Error: error during flush.
    at DerivedLogger.logger.flush (/Users/stefan/projects/helix-resolve-git-ref/test/index.test.js:172:13)
    at main (/Users/stefan/projects/helix-resolve-git-ref/src/index.js:45:321)
    at process._tickCallback (internal/process/next_tick.js:68:7)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 index.js |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**To Reproduce**
1. run `npm test`

**Additional context**
This a regression of #22

**Comment by tripodsan** [comment]
the tests are not broken, but the output looks a bit unfortunate, because we don't use the normal text reporter anymore.

if we remove the junit reporter, the output looks ok:

```
$ npm test

> @adobe/helix-resolve-git-ref@1.2.0 test helix-resolve-git-ref
>  nyc --reporter=text --reporter=lcov --check-coverage --branches 100 --statements 100 --lines 100 mocha



  main tests
    ✓ main function is present
INFO  - no external loggers configured.
    ✓ main function returns an object
INFO  - no external loggers configured.
    ✓ main function returns 404 for missing owner param
INFO  - no external loggers configured.
    ✓ main function returns 404 for missing repo param
INFO  - no external loggers configured.
    ✓ ref param is optional with default: master (626ms)
INFO  - no external loggers configured.
    ✓ main function returns valid sha format (588ms)
INFO  - no external loggers configured.
INFO  - no external loggers configured.
    ✓ main function support short and full ref names (1171ms)
INFO  - no external loggers configured.
INFO  - no external loggers configured.
    ✓ main function resolves tag (1907ms)
INFO  - no external loggers configured.
    ✓ main function returns correct sha (1334ms)
INFO  - no external loggers configured.
    ✓ main function returns 404 for non-existing ref (960ms)
INFO  - no external loggers configured.
    ✓ main function returns 404 for non-existing repo (569ms)
INFO  - no external loggers configured.
    ✓ main function returns 503 for network errors
INFO  - no external loggers configured.
    ✓ main function returns 502 for 5xx github server errors
INFO  - no external loggers configured.
    ✓ main() without parameters reports status (611ms)
[c7366f4d-8cca-467e-a281-fccd46f179ee] info: no external loggers configured.
[c7366f4d-8cca-467e-a281-fccd46f179ee] info: instrumenting epsagon.
    ✓ index function instruments epsagon (96ms)
[3795b371-b581-46f4-9cee-ded95d5be3da] info: no external loggers configured.
Error: error during flush.
    at DerivedLogger.logger.flush (~/helix-resolve-git-ref/test/index.test.js:172:13)
    at main (~/helix-resolve-git-ref/src/index.js:45:313)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    ✓ error in main function is caught


  16 passing (8s)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 index.js |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by tripodsan** [comment]
suggest to change the `package.json` like this:

```diff
$ git diff
diff --git a/package.json b/package.json
index 1ace616..f6599d4 100644
--- a/package.json
+++ b/package.json
@@ -4,8 +4,8 @@
   "description": "An OpenWhisk Web Action that resolves a git reference (branch or tag) to the corresponding commit sha.",
   "main": "src/index.js",
   "scripts": {
-    "test": " nyc --reporter=text --reporter=lcov --check-coverage --branches 100 --statements 100 --lines 100 mocha --reporter xunit --reporter-options output=./junit/test-results.xml",
-    "test-ci": "npm run test && codecov",
+    "test": " nyc --reporter=text --reporter=lcov --check-coverage --branches 100 --statements 100 --lines 100 mocha",
+    "test-ci": "nyc --reporter=text --reporter=lcov --check-coverage --branches 100 --statements 100 --lines 100 mocha --reporter xunit --reporter-options output=./junit/test-results.xml && codecov",
     "lint": "./node_modules/.bin/eslint .",
     "semantic-release": "semantic-release",
     "semantic-prepare": "node ./build/prepare.js",
@@ -78,4 +78,4 @@
     "name": "helix-services/resolve-git-ref@1.2.0",
     "static": []
   }
```
